rooklift/nibbler

9_renderer.js
Autoscroll the movelist. At the same time, correct some dubious choice to use direct DOM manipulation when, so it seems, setting innerHTML is actually faster.
=> Autoscroll

9_renderer.js, nibbler.css
Movelist performance improvements. Fairly ugly code.
=> Movelist performance

91_infobox.js, 95_renderer.js, nibbler.html
But still uses a bunch of state from renderer
=> Infobox handler

10_globals.js, 91_infobox.js, 95_renderer.js, 99_start.js, main.js, nibbler.css, nibbler.html
Drag and drop - apparently working.
=> Drag and drop

20_utils.js, 80_info.js, 95_renderer.js, 99_start.js, config.example.json, main.js, modules/load_config.js, nibbler.css
Searchmoves support in Serious Analysis Mode (tm)
=> Searchmoves

10_globals.js, 80_info.js, 95_renderer.js, 99_start.js, nibbler.css, nibbler.html, package-lock.json, package.json
Right click on moves (anywhere) to show a hypothetical board.
=> Hypothetical board

95_renderer.js, main.js
This allows selecting number of threads. By default leela is using 2 threads.
=> select number of threads

10_globals.js, 95_renderer.js, 99_start.js, nibbler.css, nibbler.html
Delete second canvas.
Also fixes an issue where double clicking on the body (in the few spots its visible) would let you select everything.
=> Delete extra canvas

30_point.js, 40_position.js, 80_info.js, 95_renderer.js
Remove the awkward Point(null) object.
=> No null point

10_globals.js, 51_winrate.js, 95_renderer.js, nibbler.html
Replace the graph SVG with a canvas
=> Canvas not SVG

20_utils.js, 80_info.js
This was a noticably slow function in profiling.
=> Replace InfoVal() function

95_renderer.js, main.js, modules/config_io.js, modules/messages.js
Restore auto-eval with a special nodes menu for it and self-play.
=> Restore auto-eval

50_node.js, 80_info.js, 95_renderer.js, package-lock.json, package.json
Store all info reported by the engine on a per node basis. Thus, when the engine is not running, going back and forward in the PGN can still display whatever info we saw last time.
=> Rememberance

src/71_tree_handler.js, src/80_info.js, src/95_renderer.js, src/main.js, src/modules/config_io.js
State rewrite, incidentally implementing locked eval position.
=> State rewrite

src/50_table.js, src/51_node.js, src/80_info.js, src/95_renderer.js
Restore the inference of PV etc when advancing. This is especially good to have with the lock feature.
=> Ghost nodes take 2

src/50_table.js, src/51_node.js, src/80_info.js, src/main.js, src/modules/config_io.js
I added the option to show WDL from white's POV, just like the POV option for eval and centipawn. I'm new to JS, but I just followed the code already in the repo.
=> added WDL from white POV option

src/71_tree_handler.js, src/95_renderer.js, src/main.js
Original PR by @Zenzizenzizenzike
=> Previous sibling command

src/main.js
This issue was fixed by specifying optional browserWindow parameter in open_dialog
=> Linux file open / save dialog appearing behind main window FIX

src/50_table.js, src/51_node.js, src/52_sorted_moves.js, src/95_hub.js
* Create the graph eval only as needed by the grapher (then cache it).
* terminal info is now stored in the table.
=> Graph rework

src/75_looker.js, src/82_infobox.js, src/main.js, src/nibbler.html
* Add Lichess API.
* Also use JSON from ChessDB.cn - fixes #175
=> Lichess API

files/scripts/install.sh
Sorry I had a minor cock-up 😅
This fix does not need a new release.
=> Fix icon paths

files/scripts/install.sh
=> fix type in install.sh

README.md
"more is better" on hash is based on https://github.com/official-stockfish/Stockfish/discussions/3333#discussioncomment-6860046
=> Add important Stockfish note

files/src/nibbler.css, files/src/renderer/99_start.js
Uses DataTransfer and CSS features to improve the user experience when dragging board pieces without performance hit, now more closely matching lichess and chess.com behavior
=> Improve piece dragging experience
